### ISSUE TITLE
Check out Google's Seurat

### ISSUE THREAD

**Issue by andybak** [Inderdeep29/UnityVR-Mesh-Optimizer#1]
https://developers.google.com/vr/discover/seurat

Things to bear in mind:

1. Oculus has a neck model for it's 3DOF SDK so the user's viewpoint will translate a small amount even without positional tracking
2. 6DOF headsets are becoming the norm. Seurat handles this by defining a box that the user's head must remain in to allow the culling to not remove polys that would be visible by leaning to one side etc.

**Comment by Inderdeep29** [comment]
Hi,
Thanks for feedback.
I checked out Seurat after a day or two it was open sourced, and decided to make this after facing the following issues during my testing of Seurat:
1. In my testing environments of around 100k triangles, it was outputting mesh of far greater amount of triangles.
2. It was producing artifacts(regarding which they have mentioned on their github page), solution to which was increasing sample size as mentioned in their docs, but I was not able to fix those artifacts even then(though they were hugely reduced) and generation time was becoming several hours after the increase in sample size.

Regarding the issues you have mentioned:
Once it becomes perfect for 3DOF, I have planned to have multiple sampling positions which should solve these problems but at the cost of time taken to generate mesh.

Further feedback/contribution is welcome.

**Comment by andybak** [comment]
Thanks. That's interesting to know. I've been meaning to play with it myself. I've just got a Lenovo Mirage and there's some use of Seurat in a couple of Google apps on that. It seems to work pretty well (full detail Google Earth 3D scenes running on mobile) but of course we don't know how much trouble it was for them to get it working correctly.

I'll follow your project with interest.
